#version: "3.8"

services:
  proxy:
  container_name: "web_proxy"
  image: nginx
  volumes:
    - /home/dck01/proxy_reverso_app_copa/proxy_conf:/etc/nginx/conf.d:ro
    - /home/dck01/proxy_reverso_app_copa/geral_page:/usr/share/nginx/html/index.html
  ports:
    - "80:80"
  
