#version: "3.8"

services:
  proxy:
    container_name: web_proxy
    image: nginx
    volumes:
      - ./proxy_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./geral_page:/usr/share/nginx/html:ro
    ports:
      - "8090:80"
  
  am_app:
      container_name: am_cup
      image: nginx
      volumes:
          - ./america_index:/usr/share/nginx/html:ro

  af_app:
      container_name: af_cup
      image: nginx
      volumes:
          - ./africa_index:/usr/share/nginx/html:ro

  eu_app:
      container_name: eu_cup
      image: nginx
      volumes:
          - ./europa_index:/usr/share/nginx/html:ro

  as_app:
      container_name: as_cup
      image: nginx
      volumes:
          - ./asia_index:/usr/share/nginx/html:ro