upstream am_cup {
    server am_cup:80;
}

upstream eu_cup {
    server eu_cup:80;
}

upstream af_cup {
    server af_cup:80;
}

upstream as_cup {
    server as_cup:80;
}

#
# América
#
server {
    listen 80;
    server_name ~^am\..+\.nip\.io$;

    location / {
        proxy_pass http://am_cup;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

#
# Europa
#
server {
    listen 80;
    server_name ~^eu\..+\.nip\.io$;

    location / {
        proxy_pass http://eu_cup;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

#
# África
#
server {
    listen 80;
    server_name ~^af\..+\.nip\.io$;

    location / {
        proxy_pass http://af_cup;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

#
# Ásia
#
server {
    listen 80;
    server_name ~^as\..+\.nip\.io$;

    location / {
        proxy_pass http://as_cup;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

#
# Qualquer outro host (*.nip.io)
#
server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}