upstream america {
    server 10.0.1.10:80;
}

upstream europa {
    server 10.0.2.10:80;
}

upstream africa {
    server 10.0.3.10:80;
}

upstream asia {
    server 10.0.4.10:80;
}

map $host $backend {
    default "";

    ~^am\..+\.nip\.io$ http://america;
    ~^eu\..+\.nip\.io$ http://europa;
    ~^af\..+\.nip\.io$ http://africa;
    ~^as\..+\.nip\.io$ http://asia;
}

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {

        if ($backend = "") {
            try_files $uri $uri/ /index.html;
            break;
        }

        proxy_pass $backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}